# Generated by Django 5.0.1 on 2024-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transactionbyphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbyphone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
